import { useState } from 'react'
import { Check, ChevronRight, Clock3, CreditCard, Heart, Info, Minus, Plus, QrCode, RotateCcw, Search, Send, Star, Users, X } from 'lucide-react'
import { go, screens, type Screen } from '../session/machine'
import { money } from '../lib/format'
import { Back, Action, Center, BillRow } from '../ui/primitives'

export function Connect({ dispatch }: any) { return <Center eyebrow="A BETTER WAY TO DINE" title={'Making the<br /><em>table</em> feel closer.'} copy="Connecting to your table at Kozo, Accra"><div className="loader" /><button className="text-link" onClick={() => dispatch(go('welcome'))}>Skip connection</button></Center> }

export function Welcome({ s, dispatch }: any) { return <section className="welcome"><div className="hero-image" /><div className="welcome-copy"><p className="eyebrow">WELCOME TO KOZO</p><h1>Good food.<br /><em>Good company.</em></h1><p className="muted">You are at table 07. Explore the menu, call your waiter, or settle your bill when you are ready.</p><Action onClick={() => dispatch(go(s.hasOrder ? 'bill' : 'empty'))}>{s.hasOrder ? 'View your live bill' : 'Explore the menu'}</Action><button className="outline-button" onClick={() => dispatch({ type: 'toggleOrder' })}>Switch to {s.hasOrder ? 'empty table' : 'active bill'} demo</button></div></section> }

export function Empty({ dispatch }: any) { return <section><Back dispatch={dispatch} to="welcome" /><p className="eyebrow">TABLE 07 · READY WHEN YOU ARE</p><h1>Your table,<br /><em>your pace.</em></h1><p className="muted">Nothing has been added yet. Browse Kozo's menu, or call someone over if you need a recommendation.</p><div className="empty-card"><QrCode /><strong>No order yet</strong><span>Your bill will appear here once the first order is placed.</span></div><Action onClick={() => dispatch(go('menu'))}>Explore the menu</Action><button className="waiter-link" onClick={() => dispatch(go('waiter'))}><Send />Ask for a recommendation</button></section> }

export function Menu({ dispatch }: any) { const items = [['Sea bass, charred lemon','GH₵145','sea-bass.png'],['Jollof arancini','GH₵70','sea-bass.png'],['Suya skewers','GH₵90','sea-bass.png'],['Yam fries & aioli','GH₵55','sea-bass.png'],['Garden salad','GH₵65','sea-bass.png'],['Sparkling water','GH₵15','sea-bass.png'],['Sobolo spritz','GH₵38','sea-bass.png'],['Chocolate fondant','GH₵85','chocolate-fondant.png']]; return <section><header className="page-header"><div><p className="eyebrow">KOZO · TABLE 07</p><h1>What are you<br /><em>in the mood for?</em></h1></div><button className="icon-button"><Search /></button></header><div className="tabs"><button className="active">All</button><button onClick={() => dispatch(go('category'))}>Small plates</button><button onClick={() => dispatch({ type: 'dish', value: 'Sea bass, charred lemon' })}>Mains</button><button onClick={() => dispatch({ type: 'dish', value: 'Chocolate fondant' })}>Dessert</button></div><div className="recommend"><div><p className="eyebrow">CHEF'S NOTE</p><h2>Worth trying tonight.</h2><p>Bright, fresh, and made for sharing.</p></div><Star /></div><div className="section-label">POPULAR NOW <span>{items.length} dishes</span></div>{items.map(([name, price, img]) => <button className="dish-row" key={name} onClick={() => dispatch({ type: 'dish', value: name })}><img src={`/assets/${img}`} alt={name} /><span><strong>{name}</strong><small>Kozo kitchen favourite</small></span><b>{price}</b><ChevronRight /></button>)}<Action secondary onClick={() => dispatch(go('bill'))}>View live bill</Action></section> }

export function Category({ dispatch }: any) { return <section><Back dispatch={dispatch} /><p className="eyebrow">KOZO MENU</p><h1>Small <em>plates</em></h1><p className="muted">A little something for everyone at the table.</p><div className="category-grid"><button onClick={() => dispatch({ type: 'dish', value: 'Crispy plantain chips' })}><span>SPICY</span><strong>Plantain<br />chips</strong><b>GH₵45</b></button><button onClick={() => dispatch({ type: 'dish', value: 'Garden salad' })}><span>FRESH</span><strong>Garden<br />salad</strong><b>GH₵65</b></button></div><div className="section-label">ALL SMALL PLATES</div><div className="simple-list"><p>Jollof arancini <b>GH₵70</b></p><p>Suya skewers <b>GH₵90</b></p><p>Yam fries & aioli <b>GH₵55</b></p></div></section> }

export function Dish({ s, dispatch }: any) { return <section><Back dispatch={dispatch} /><img className="dish-hero" src={`/assets/${s.dish.includes('bass') ? 'sea-bass.png' : 'chocolate-fondant.png'}`} alt={s.dish} /><p className="eyebrow">KOZO KITCHEN</p><h1>{s.dish}</h1><p className="price">{s.dish.includes('Chocolate') ? 'GH₵85' : s.dish.includes('arancini') ? 'GH₵70' : s.dish.includes('Suya') ? 'GH₵90' : s.dish.includes('Yam') ? 'GH₵55' : s.dish.includes('salad') ? 'GH₵65' : s.dish.includes('water') ? 'GH₵15' : 'GH₵145'}</p><p className="muted">A beautiful plate with bright citrus, garden herbs, and the kind of care you can taste in every bite.</p><div className="tags"><span>Gluten free</span><span>Chef favourite</span></div><Action onClick={() => dispatch(go('waiter'))}>Ask your waiter about this dish</Action></section> }

export function Waiter({ dispatch }: any) { return <section><Back dispatch={dispatch} to="empty" /><p className="eyebrow">WAITER ASSISTANCE</p><h1>What can we<br /><em>help with?</em></h1><p className="muted">A member of the Kozo team will be with you shortly.</p><div className="sheet-options"><button onClick={() => dispatch({ type: 'waiter' })}><Send /><span><b>Call my waiter</b><small>Someone will come to your table</small></span><ChevronRight /></button><button onClick={() => dispatch({ type: 'waiter' })}><Info /><span><b>Recommend a dish</b><small>Get a little local expertise</small></span><ChevronRight /></button></div></section> }

export function WaiterNotified({ dispatch }: any) { return <Center eyebrow="REQUEST SENT" title={'On the<br /><em>way.</em>'} copy="Your waiter has been notified. No need to wave — we will come to you."><div className="notice-card"><Clock3 /><span>Usually within 2–3 minutes</span></div><Action onClick={() => dispatch(go('waiting-bill'))}>Wait for my bill</Action><button className="text-link" onClick={() => dispatch(go('menu'))}>Back to menu</button></Center> }

export function WaitingBill({ dispatch }: any) { return <Center eyebrow="BILL REQUESTED" title={'We are<br /><em>on it.</em>'} copy="Your bill will appear here once your waiter closes the table."><div className="loader" /><button className="demo-control" onClick={() => dispatch(go('bill-ready'))}>Demo: bill is ready</button></Center> }

export function Bill({ dispatch, ready = false }: any) { return <section><Back dispatch={dispatch} to={ready ? 'bill-ready' : 'welcome'} /><p className="eyebrow">TABLE 07 · LIVE BILL</p><h1>Your table,<br /><em>so far.</em></h1><div className="bill-card"><div className="status"><span className="pulse" />{ready ? 'Bill ready from Kozo POS' : 'Live from Kozo POS'} <Clock3 /></div><p>2 guests · Started 7:42 PM</p><BillRow name="Sea bass, charred lemon" qty="1" price={145} /><BillRow name="Jollof arancini" qty="2" price={140} /><BillRow name="Sparkling water" qty="2" price={30} /><div className="bill-total"><span>Subtotal</span><b>{money(315)}</b></div><div className="bill-total"><span>Service charge</span><span>{money(31.5)}</span></div><div className="grand-total"><span>Total so far</span><b>{money(346.5)}</b></div></div><button className="waiter-link" onClick={() => dispatch(go('waiter'))}><Send />Call your waiter</button><button className="waiter-link" onClick={() => dispatch(go('bill-issue'))}><Info />Report a problem with the bill</button><Action onClick={() => dispatch(go('full-check'))}>See full check</Action></section> }

export function FullCheck({ dispatch }: any) { return <section><Back dispatch={dispatch} to="bill" /><p className="eyebrow">FULL CHECK · TABLE 07</p><h1>Everything<br /><em>looks good.</em></h1><div className="receipt-card"><BillRow name="Dinner for 2" qty="" price={315} /><BillRow name="Service charge" qty="" price={31.5} /><div className="grand-total"><span>Total</span><b>{money(346.5)}</b></div></div><Action onClick={() => dispatch(go('recommendation'))}>Continue</Action></section> }

export function Recommendation({ dispatch }: any) { return <section><Back dispatch={dispatch} to="full-check" /><p className="eyebrow">BEFORE YOU GO</p><h1>One last<br /><em>little thing?</em></h1><div className="recommend-card"><img src="/assets/chocolate-fondant.png" alt="Chocolate fondant" /><div><p className="eyebrow">DESSERT</p><h2>Chocolate fondant</h2><p>Warm centre, sea salt, pure joy.</p><b>GH₵85</b></div></div><Action onClick={() => dispatch(go('pay'))}>Settle the bill</Action><button className="outline-button" onClick={() => dispatch(go('dish'))}>View dessert details</button></section> }

export function Pay({ dispatch }: any) { return <section><Back dispatch={dispatch} to="recommendation" /><p className="eyebrow">SETTLE UP</p><h1>How would you<br /><em>like to pay?</em></h1><div className="pay-total"><span>Your share</span><strong>{money(346.5)}</strong></div><button className="choice" onClick={() => dispatch({ type: 'patch-go', value: { shareMode: 'full' }, to: 'tip' })}><span className="choice-icon"><CreditCard /></span><span><b>Pay the full bill</b><small>One simple payment</small></span><ChevronRight /></button><button className="choice" onClick={() => dispatch(go('split'))}><span className="choice-icon"><Users /></span><span><b>Split the bill</b><small>Everyone pays their share</small></span><ChevronRight /></button></section> }

export function Split({ dispatch }: any) { const [people, setPeople] = useState(2); const [mode, setMode] = useState<'even' | 'custom' | 'invite'>('even'); return <section><Back dispatch={dispatch} to="pay" /><p className="eyebrow">SPLIT THE BILL</p><h1>Make it <em>easy.</em></h1><p className="muted">Choose how everyone at the table can settle their share.</p><div className="split-modes"><button className={mode === 'even' ? 'selected' : ''} onClick={() => setMode('even')}>Even split<small>Everyone pays the same</small></button><button className={mode === 'custom' ? 'selected' : ''} onClick={() => setMode('custom')}>Custom split<small>Choose what you owe</small></button><button className={mode === 'invite' ? 'selected' : ''} onClick={() => setMode('invite')}>Invite others<small>Share a payment link</small></button></div>{mode !== 'invite' && <><div className="stepper"><button aria-label="Remove person" onClick={() => setPeople(Math.max(2, people - 1))}><Minus /></button><strong>{people}</strong><button aria-label="Add person" onClick={() => setPeople(people + 1)}><Plus /></button></div><div className="split-share"><span>{mode === 'custom' ? 'Your custom share' : 'Each person pays'}</span><b>{money(mode === 'custom' ? 120 : 346.5 / people)}</b></div></>}<Action onClick={() => dispatch({ type: 'patch-go', value: { shareMode: mode, people, customAmountPesewas: mode === 'custom' ? 12000 : undefined }, to: 'split-share' })}>{mode === 'invite' ? 'Create invite' : 'Continue'}</Action></section> }

export function Tip({ dispatch }: any) { return <section><Back dispatch={dispatch} to="pay" /><p className="eyebrow">A LITTLE EXTRA</p><h1>Leave a<br /><em>tip?</em></h1><p className="muted">100% goes directly to the Kozo team.</p><div className="tip-grid">{[0, 5, 10, 15].map(n => <button className={n === 10 ? 'selected' : ''} key={n} onClick={() => dispatch({ type: 'patch-go', value: { tipPercent: n }, to: 'review' })}>{n === 0 ? 'No tip' : `${n}%`}<small>{n ? money(346.5 * n / 100) : ''}</small></button>)}</div><Action onClick={() => dispatch({ type: 'patch-go', value: { tipPercent: 10 }, to: 'review' })}>Review payment</Action></section> }

export function Review({ dispatch }: any) { return <section><Back dispatch={dispatch} to="tip" /><p className="eyebrow">REVIEW PAYMENT</p><h1>Ready when<br /><em>you are.</em></h1><div className="summary-card"><div><span>Bill</span><b>{money(346.5)}</b></div><div><span>Tip · 10%</span><b>{money(34.65)}</b></div><div className="grand-total"><span>Total</span><b>{money(381.15)}</b></div></div><Action onClick={() => dispatch(go('method'))}>Choose payment method</Action></section> }

export function Method({ dispatch }: any) { return <section><Back dispatch={dispatch} to="review" /><p className="eyebrow">PAYMENT METHOD</p><h1>Almost<br /><em>there.</em></h1><div className="summary-line"><span>Total</span><b>{money(381.15)}</b></div><button className="choice selected"><span className="choice-icon momo">M</span><span><b>Mobile Money</b><small>MTN MoMo, Vodafone, AirtelTigo</small></span><Check /></button><button className="choice" onClick={() => dispatch({ type: 'patch-go', value: { method: 'card' }, to: 'processing' })}><span className="choice-icon"><CreditCard /></span><span><b>Bank card</b><small>Visa, Mastercard · demo</small></span><ChevronRight /></button><Action onClick={() => dispatch({ type: 'patch-go', value: { method: 'momo' }, to: 'momo' })}>Continue</Action></section> }

export function Momo({ dispatch, error = false }: any) { const [number, setNumber] = useState(''); return <section><Back dispatch={dispatch} to="method" /><p className="eyebrow">MOBILE MONEY · TRANSACTION ONLY</p><h1>Enter your<br /><em>number.</em></h1><p className="muted">This number is only used to send the payment prompt. We will not save it.</p>{error && <div className="error"><X />Payment didn&apos;t go through. Check your balance and try again.<div className="error-actions"><button onClick={() => dispatch(go('authorise'))}>Retry payment</button><button onClick={() => dispatch(go('method'))}>Change method</button></div></div>}<label className="field-label">Mobile number<input value={number} onChange={e => setNumber(e.target.value)} placeholder="024 000 0000" inputMode="tel" /></label><Action onClick={() => dispatch(number ? { type: 'patch-go', value: { momoNumber: number, method: 'momo' }, to: 'authorise' } : { type: 'error' })}>Continue</Action></section> }

export function PaymentOtp({ dispatch }: any) { const [otp, setOtp] = useState(''); return <section><Back dispatch={dispatch} to="method" /><p className="eyebrow">CARD VERIFICATION</p><h1>Check your<br /><em>messages.</em></h1><p className="muted">Enter the one-time code from your bank to continue. This is only for this payment.</p><input className="otp" value={otp} onChange={e => setOtp(e.target.value)} placeholder="123456" inputMode="numeric" aria-label="Payment verification code" /><Action onClick={() => dispatch({ type: 'pay-otp', value: { otp } })}>Verify payment</Action></section> }

export function Authorise({ dispatch }: any) { return <Center eyebrow="CHECK YOUR PHONE" title={'Approve the<br /><em>payment.</em>'} copy="A prompt is waiting on your mobile money phone. Enter your PIN to approve GH₵381.15." icon="M"><Action onClick={() => dispatch(go('processing'))}>I&apos;ve approved it</Action><button className="text-link" onClick={() => dispatch(go('momo'))}>Use a different number</button></Center> }

export function Processing({ dispatch }: any) { return <Center eyebrow="SECURE PAYMENT" title={'Making it<br /><em>official.</em>'} copy="Confirming your payment with MTN MoMo..."><div className="loader large" /><button className="demo-control" onClick={() => dispatch({ type: 'pay-mock', outcome: 'captured' })}>Demo: complete payment</button><button className="text-link" onClick={() => dispatch({ type: 'pay-mock', outcome: 'failed' })}>Demo: failed payment</button></Center> }

export function Success({ dispatch }: any) { return <Center eyebrow="PAYMENT COMPLETE" title={'You&apos;re all<br /><em>settled.</em>'} copy="Thanks for dining at Kozo. Your receipt is ready whenever you are." icon="✓"><Action onClick={() => dispatch(go('receipt-choice'))}>View receipt options</Action></Center> }

export function ReceiptChoice({ s, dispatch }: any) { return <section><p className="eyebrow">KOZO · RECEIPT {s?.receiptNumber ?? '#2841'}</p><h1>Keep a little<br /><em>memory.</em></h1><div className="receipt-card"><div className="receipt-head"><span>Kozo</span><b>PAID</b></div><p>Tuesday, 26 August 2026 · 9:16 PM</p><div className="grand-total"><span>Total paid</span><b>{money((s?.totalPaidPesewas ?? 38115) / 100)}</b></div></div><Action onClick={() => dispatch(go('phone'))}>Save receipt & earn rewards</Action><button className="outline-button" onClick={() => dispatch(go('guest-receipt'))}>Continue as guest</button></section> }

export function Phone({ dispatch }: any) { const [phone, setPhone] = useState(''); return <section><Back dispatch={dispatch} to="receipt-choice" /><p className="eyebrow">OPTIONAL · REWARDS</p><h1>Where should we<br /><em>send it?</em></h1><p className="muted">Save your receipt and collect Kozo rewards. No account or sign-in needed.</p><label className="field-label">Phone number<input value={phone} onChange={e => setPhone(e.target.value)} placeholder="024 000 0000" inputMode="tel" /></label><Action onClick={() => dispatch({ type: 'otp-send', value: { phone } })}>Send verification code</Action></section> }

export function OtpRewards({ dispatch }: any) { const [code, setCode] = useState(''); return <section><Back dispatch={dispatch} to="phone" /><p className="eyebrow">VERIFY YOUR NUMBER</p><h1>Check your<br /><em>messages.</em></h1><p className="muted">Enter the six-digit demo code sent to your phone.</p><input className="otp" value={code} onChange={e => setCode(e.target.value)} placeholder="123456" inputMode="numeric" /><Action onClick={() => dispatch({ type: 'otp-verify', value: { code } })}>Verify number</Action></section> }

export function Name({ dispatch }: any) { const [name, setName] = useState(''); return <section><Back dispatch={dispatch} to="otp-rewards" /><p className="eyebrow">OPTIONAL</p><h1>One name,<br /><em>if you like.</em></h1><p className="muted">Personalise your next Kozo visit. You can skip this.</p><label className="field-label">Your name<input value={name} onChange={e => setName(e.target.value)} placeholder="Ama" /></label><Action onClick={() => dispatch({ type: 'rewards-consent', value: { firstName: name } })}>Save rewards</Action><button className="outline-button" onClick={() => dispatch({ type: 'rewards-consent', value: {} })}>Skip for now</button></section> }

export function Rewards({ dispatch }: any) { return <Center eyebrow="REWARDS SAVED" title={'See you<br /><em>again.</em>'} copy="Your receipt is saved and 120 Kozo points have been added." icon="★"><Action onClick={() => dispatch(go('feedback'))}>Share feedback</Action></Center> }

export function GuestReceipt({ s, dispatch }: any) { return <section><p className="eyebrow">GUEST RECEIPT · {s?.receiptNumber ?? '#2841'}</p><h1>All <em>done.</em></h1><div className="receipt-card"><div className="receipt-head"><span>Kozo</span><b>PAID</b></div><p>Your receipt is available for this session.</p><div className="grand-total"><span>Total paid</span><b>{money((s?.totalPaidPesewas ?? 38115) / 100)}</b></div></div><Action onClick={() => dispatch(go('feedback'))}>Continue</Action></section> }

export function Feedback({ dispatch }: any) { return <section className="center-screen"><Heart className="heart" /><p className="eyebrow">ONE LAST THING</p><h1>How was your<br /><em>Kozo moment?</em></h1><div className="stars">{[1,2,3,4,5].map(i => <button key={i} onClick={() => dispatch({ type: 'feedback', value: { rating: i } })}><Star /></button>)}</div><p className="muted">Tap a star to share how it felt.</p><button className="text-link" onClick={() => dispatch(go('complete'))}>Maybe later</button></section> }

export function ReviewHandoff({ s, dispatch }: any) { return <Center eyebrow="THANK YOU" title={'Would you tell<br /><em>Google too?</em>'} copy="You rated us highly — a quick public review helps other diners find Kozo. It opens in a new tab." icon="★"><Action onClick={() => { try { if (s?.reviewUrl) window.open(s.reviewUrl, '_blank', 'noopener') } catch {} dispatch(go('complete')) }}>Leave a Google review</Action><button className="text-link" onClick={() => dispatch(go('complete'))}>No thanks</button></Center> }

export function Complete({ dispatch }: any) { return <Center eyebrow="THANK YOU" title={'Until the<br /><em>next one.</em>'} copy="Your feedback helps us make every table feel closer."><button className="demo-control" onClick={() => dispatch({ type: 'reset' })}><RotateCcw />Start again</button></Center> }

export function SplitShare({ dispatch }: any) { return <section><Back dispatch={dispatch} to="split" /><p className="eyebrow">YOUR SHARE</p><h1>That&apos;s <em>fair.</em></h1><div className="pay-total"><span>2 people splitting</span><strong>{money(173.25)}</strong></div><Action onClick={() => dispatch(go('tip'))}>Continue</Action></section> }

export function Handoff({ dispatch }: any) { return <div className="review-page"><header><p className="eyebrow">KLOWN PAY · UX HANDOFF</p><h1>Thirty-five screens.<br /><em>One closer table.</em></h1><p className="muted">A presentation-layer prototype for Claude implementation. Every state is simulated locally.</p></header><div className="handoff-grid"><section><h2>Flow map</h2><p>QR arrival → menu or bill → assistance → check → recommendation → split/full pay → MoMo → receipt → rewards → feedback.</p><div className="flow-lines">{['Journey A · No order yet','Journey B · Bill available','Post-payment · Rewards or guest'].map((x, i) => <button key={x} onClick={() => { window.location.hash = ''; dispatch(go(i === 0 ? 'empty' : i === 1 ? 'bill' : 'receipt-choice')) }}>{x}<ChevronRight /></button>)}</div></section><section><h2>Design system</h2><div className="token-row"><span className="token swatch-brand" />Ink / #181816</div><div className="token-row"><span className="token swatch-accent" />Kozo yellow / #F3C744</div><div className="token-row"><span className="token swatch-bg" />Warm paper / #F7F5F0</div><p className="handoff-copy">Typography uses a crisp sans for utility and an editorial serif italic for emotional moments. Actions are full-width, sticky in the mobile safe area, and limited to one primary CTA.</p></section></div><h2>Screen inventory</h2><div className="inventory">{screens.map(([id, name, section, entry, primary, next]) => <button key={id} onClick={() => { window.location.hash = ''; dispatch(go(id)) }}><span>{name}</span><small>{section} · {entry}</small><b>{primary} → {next}</b></button>)}</div></div> }

export function BillIssue({ dispatch }: any) { const reasons = ['An item looks wrong', 'I was charged twice', "This isn't our table's bill", 'Something else']; return <section><Back dispatch={dispatch} to="bill" /><p className="eyebrow">BILL SUPPORT</p><h1>What looks<br /><em>off?</em></h1><p className="muted">Tell us what to check and a Kozo team member will come over. Your bill is never changed from your phone.</p><div className="sheet-options">{reasons.map((r) => <button key={r} onClick={() => dispatch({ type: 'dispute', note: r })}><Info /><span><b>{r}</b></span><ChevronRight /></button>)}</div></section> }

export const map: Record<string, any> = { connect: Connect, welcome: Welcome, empty: Empty, menu: Menu, category: Category, dish: Dish, waiter: Waiter, 'waiter-notified': WaiterNotified, 'waiting-bill': WaitingBill, 'bill-ready': (p: any) => <Bill {...p} ready />, bill: Bill, 'bill-issue': BillIssue, 'full-check': FullCheck, recommendation: Recommendation, pay: Pay, split: Split, 'split-share': ({ dispatch }: any) => <SplitShare dispatch={dispatch} />, tip: Tip, review: Review, method: Method, momo: Momo, otp: PaymentOtp, authorise: Authorise, processing: Processing, 'payment-error': (p: any) => <Momo {...p} error />, success: Success, 'receipt-choice': ReceiptChoice, phone: Phone, 'otp-rewards': OtpRewards, name: Name, rewards: Rewards, 'guest-receipt': GuestReceipt, feedback: Feedback, 'review-handoff': ReviewHandoff, complete: Complete }
